# Generated by Django 4.2.2 on 2023-08-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('capacity', models.IntegerField()),
                ('projector', models.BooleanField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=225)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervation.rooms')),
            ],
            options={
                'unique_together': {('date', 'room')},
            },
        ),
    ]
